name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: nextflow
        channels: conda-forge,bioconda,defaults
    - name: setup
      shell: bash -l {0}
      run: conda install --yes --quiet nextflow procps-ng
    - name: test
      shell: bash -l {0}
      run: | 
        nextflow run main.nf --help
        nextflow run main.nf -profile conda --wget --accession_list=tests/wget.txt --out_dir="results" -c tests/test.conf
        test -f results/SRR4238351_subsamp.fastq.gz
        nextflow run main.nf -profile conda --sra --accession_list=tests/sra.txt --out_dir="results" -c tests/test.conf --sracpus 2
        test -f results/SRR4216351.fastq.gz
        nextflow run main.nf --gdc --gdc_file_id 57c425f6-9625-407e-93b8-1d03858fd1f6,00cdff29-697a-4a17-ba67-cf55c006b827 --out_dir="results" -c tests/test.conf
        test -f results/57c425f6-9625-407e-93b8-1d03858fd1f6/576325e7-0f30-406c-9147-80e3edcf8b57.rna_seq.augmented_star_gene_counts.tsv && \
          test -f results/00cdff29-697a-4a17-ba67-cf55c006b827/0f35c851-1cb8-4f75-a661-eae9111b7362.rna_seq.augmented_star_gene_counts.tsv
        nextflow run main.nf --gdc --gdc_manifest tests/gdc_manifest_1.txt --out_dir="results" -c tests/test.conf
        test -f results/a77adf63-487b-476e-bd33-903005c1dba9/12b633ae-2a36-40b0-a4a3-c1d5f021fa23.rna_seq.augmented_star_gene_counts.tsv 
        nextflow run main.nf --gdc --gdc_file_id tests/gdc_file_id_list.txt --out_dir="results" -c tests/test.conf
        test -f results/b064b6be-4152-4737-8158-caa0454cf41b/f279a2fa-6d1b-476c-b91b-598f5c1bbc34.rna_seq.augmented_star_gene_counts.tsv && \
          test -f results/3456d4a1-bb29-4559-8c4e-c9b0e512fae3/52472301-36c6-4c99-97bd-b016d8a282d6.rna_seq.augmented_star_gene_counts.tsv
